services:
  nginx:
    image: nginx:stable
    ports: ["8080:80"]
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [api]

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
