version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
      POSTGRES_DB: weatherdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    restart: always
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
      POSTGRES_DB: weatherdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      WEATHER_API_KEY: 19140bf7651518fe664ab81d5c45ed7a
    depends_on:
      - db
    ports:
      - "8000:8000"


  nginx:
    image: nginx:stable
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api

volumes:
  pgdata:
